### ISSUE TITLE
Migration from jnimmo doesn´t work.

### ISSUE THREAD

**Issue by cristianm** [Breina/ha-artnet-led#10]
Dear, I can't get the DMX management to work. Previously I was using the jnimmo script with no problems.

I uninstalled it, updated HA and installed yours, but unfortunately I can't get it to work.

This is the OLD config:

light:
  - platform: dmx
    host: X.X.X.X
    send_levels_on_startup: true
    default_level: 255
    dmx_channels: 512
    devices:
      - channel: 1
        name: Hall 1
      - channel: 2
        name: Hall 2
      - channel: 3
        name: Living 1
      - channel: 4
        name: Living 2
      - channel: 5
        name: Living 3
      - channel: 6
        name: Living 4
      - channel: 7
        name: Living 5
      - channel: 8
        name: Living 6
      - channel: 9
        name: Living 7
      - channel: 10
        name: Living 8
      - channel: 11
        name: Pasillo (Living)
      - channel: 12
        name: Pasillo (Cocina)
      - channel: 13
        name: Baño (Espejo)
      - channel: 14
        name: Baño (General)
      - channel: 15
        name: Asador
      - channel: 16
        name: Portada
      - channel: 17
        name: Galeria
      - channel: 128
        type: rgb
        name: Pileta
      - channel: 132
        type: rgb
        name: Arbol 1

This is the new config:

light:
- platform: artnet_led
  host: X.X.X.X
  universes:
    0: 
      devices:
        - channel: 1
          name: Hall 1 
          type: dimmer
        - channel: 2
          name: Hall 2
          type: dimmer
        - channel: 3
          name: Living 1
          type: dimmer
        - channel: 4
          name: Living 2
          type: dimmer
        - channel: 5
          name: Living 3
          type: dimmer
        - channel: 6
          name: Living 4
          type: dimmer
        - channel: 7
          name: Living 5
          type: dimmer
        - channel: 8
          name: Living 6
          type: dimmer
        - channel: 9
          name: Living 7
          type: dimmer
        - channel: 10
          name: Living 8
          type: dimmer
        - channel: 11
          name: Pasillo (Living)
          type: dimmer
        - channel: 12
          name: Pasillo (Cocina)
          type: dimmer
        - channel: 13
          name: Baño (Espejo)
          type: dimmer
        - channel: 14
          name: Baño (General)
          type: dimmer
        - channel: 15
          name: Asador
          type: dimmer
        - channel: 16
          name: Portada
          type: dimmer
        - channel: 17
          name: Galeria
          type: dimmer
        - channel: 128
          name: Pileta
          type: rgb
        - channel: 132
          name: Arbol 1
          type: rgb

**Comment by cristianm** [comment]
I try use pyartnet directly without success. 

import asyncio

async def make_universe():
    from pyartnet import ArtNetNode
    
    # Run this code in your async function
    node = ArtNetNode('X.X.X.X')
    await node.start()

    # Create universe 0
    universe = node.add_universe(0)
	
    channel  = universe.add_channel(start=1, width=1)
    channel.add_fade([255], 5000)

    await channel.wait_till_fade_complete()


asyncio.run(make_universe())

**Comment by Breina** [comment]
Can you please check the logs and tell me what kind of error you are seeing?

>I uninstalled it, updated HA and installed yours

Can you confirm that you did all the steps from the migration guide here? https://github.com/Breina/ha-artnet-led#installation

Not deleting previous entities in between swapping repository is known to cause problems.

**Comment by cristianm** [comment]
Yes, I run all the steps. I see isues with the library. I run directly the code without success:

async def make_universe():
from pyartnet import ArtNetNode

node = ArtNetNode('X.X.X.X')
await node.start()

universe = node.add_universe(0)

channel  = universe.add_channel(start=1, width=1)
channel.add_fade([255], 5000)

await channel.wait_till_fade_complete()
asyncio.run(make_universe())

**Comment by Breina** [comment]
Please update to v0.0.6 to see if that fixes it. I upgraded the required library version, hoping that will trigger a re-download in HA.

**Comment by cristianm** [comment]
The version 0.8.4 is the one used in the test with the code of the example. I don´t know the diference with the other addon that doesn´t use the library.

**Comment by Breina** [comment]
This is the simplest possible implementation of both, can you please check both? The only real difference is the sequence, which is implemented in pyartnet and always 0 in jnimmo's.

Set your host and port (default port is 6454 for artnet), and test if sequence number matters. If both work, then it's something internal into the library and I will investigate further.

## jnimmo

import socket
import struct

```
host = "x.x.x.x"
port = 6454
universe_nr = 0
highest_channel = 1
data = bytearray()
data.append(255)

packet = bytearray()
packet.extend(map(ord, "Art-Net"))
packet.append(0x00)  # Null terminate Art-Net
packet.extend([0x00, 0x50])  # Opcode ArtDMX 0x5000 (Little endian)
packet.extend([0x00, 0x0E])  # Protocol version 14
packet.extend([0x00, 0x00])  # Sequence, Physical
packet.extend([universe_nr, 0x00])  # Universe
packet.extend(struct.pack(">h", highest_channel))
packet.extend(data)

socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)  # UDP
socket.sendto(packet, (host, port))
```

## pyartnet

```
import struct
import socket

host = "x.x.x.x"
port = 6454
universe_nr = 0
sequence_counter = 0 # jnimmo's is always 0, pyartnet is [0, 254], which is compliant with the spec
highest_channel = 1
data = bytearray()
data.append(255)

packet = bytearray()
packet.extend(map(ord, "Art-Net"))
packet.append(0x00)  # Null terminate Art-Net
packet.extend([0x00, 0x50])  # Opcode ArtDMX 0x5000 (Little endian)
packet.extend([0x00, 0x0e])  # Protocol version 14
packet.append(sequence_counter)  # Sequence,
packet.append(0x00)  # Physical
packet.append(universe_nr & 0xFF)  # Universe LowByte
packet.append(universe_nr >> 8 & 0xFF)  # Universe HighByte
packet.extend(struct.pack('>h', highest_channel))
packet.extend(data)

socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)  # UDP
socket.setblocking(False)
socket.sendto(packet, (host, port))
```

**Comment by cristianm** [comment]
None of this works for me. I don´t understand why. The jnimmo addon works fine, but this script doesn´t work.

**Comment by cristianm** [comment]
If you need can access to my desktop via anydesk and view in live. Or I can send my telegram to view directly with you.

**Comment by Breina** [comment]
Does it accept the request and just doesn't do anything? Or do you get a connection error? Please double check the IP and port.
Play around a bit with the variables so see if anything sticks.

The top one is ripped from jnimmo's implementation, so if that doesn't work, I expect something else is going on here.

I'll keep your anydesk option into consideration for now, currently don't have time available for a remote coding session.

**Comment by cristianm** [comment]
> Does it accept the request and just doesn't do anything? Or do you get a connection error? Please double check the IP and port. Play around a bit with the variables so see if anything sticks.
> 
> The top one is ripped from jnimmo's implementation, so if that doesn't work, I expect something else is going on here.
> 
> I'll keep your anydesk option into consideration for now, currently don't have time available for a remote coding session.

The script doesn´t show any error, run and exit, but nothing happen with the light. If I use it from HA and the old plugin, works fine.

**Comment by cristianm** [comment]
I use same host that with the plugin of jnimmo. With the plugin of jnimmo i not setup the port, so use default port

**Comment by Breina** [comment]
Is it possible for you to install https://www.lightjams.com/artnetominator/, open it on a computer and configure HA with the IP address of your computer?

That way we could rule out the configuration being erroneous.

**Comment by cristianm** [comment]
I test again and currently doesn´t work:

Some values are bad here. Why a Dimmer channel have "DMX Channels 3" ?

![image](https://user-images.githubusercontent.com/1960385/198837626-6b3397b6-1e82-444d-b815-96d0e1b5a4f2.png)

**Comment by cristianm** [comment]
> Is it possible for you to install https://www.lightjams.com/artnetominator/, open it on a computer and configure HA with the IP address of your computer?
> 
> That way we could rule out the configuration being erroneous.

With the artnetominator works. But with my wifi to dmx controller don´t and the jnimmo yes. I don´t know the diference, maybe the dmx library.

**Comment by cristianm** [comment]
For example, with FreeStyler i command without issue too

**Comment by cristianm** [comment]
any new about this?

**Comment by Breina** [comment]
Sorry I haven't had much time to work on this, and I've been missing it as well. I'll try to free up some time.

**Comment by Breina** [comment]
@cristianm Made some great progress in the last week, keep holding on for a little while more please!

**Comment by cristianm** [comment]
> @cristianm Made some great progress in the last week, keep holding on for a little while more please!

Excelent. I wait for news.

**Comment by Breina** [comment]
@cristianm One of the users on the DMX lighting forum thread made a discovery that may fix it for you as well.

Please upgrade to `v0.0.13` and use `send_partial_universe=False` and let me know if that helps. New client still ongoing meanwhile.

**Comment by cristianm** [comment]
Works now!!!! Yeah!

How I can set default value to 255 to every channel?

**Comment by Breina** [comment]
Nice! [Give Gruffalo34 some love for finding this](https://community.home-assistant.io/t/dmx-lighting/2248/332?u=breina). :)

You're right it wasn't very clear how to do that. I've updated the README on the static values a bit, to make it more clear. [Have a look please](https://github.com/Breina/ha-artnet-led#channel_setup).
