### ISSUE TITLE
@jnimmo's rgbw_auto missing

### ISSUE THREAD

**Issue by tobias-friedrich** [Breina/ha-artnet-led#11]
[@jnimmo](https://github.com/jnimmo/hass-dmx) offered the type **rgbw_auto** for automatically calculating the white value. Any chance to include this here, too? Thanks!

**Comment by Breina** [comment]
Alright, fixed in v0.0.6. Just add `channel_setup: rgbw` to an light with `type: rgb`.

Actually pretty cool feature, going to use this myself as well. :)
