### ISSUE TITLE
Unique IDs when using multiple DMX controllers

### ISSUE THREAD

**Issue by tobias-friedrich** [Breina/ha-artnet-led#12]
I just moved from [@jnimmo](https://github.com/jnimmo/hass-dmx) and observed that this fork does not support reusing DMX channels on multiple DMX controllers. I have three controllers:
```
light:
  - platform: artnet_led
    host: 192.168.0.20
    universes:
      0:
        devices:
          - channel: 1
...
  - platform: artnet_led
    host: 192.168.0.44
    universes:
      0:
        devices:
          - channel: 1
...
  - platform: artnet_led
    host: 192.168.0.21
    universes:
      0:
        devices:
          - channel: 1
```

In [@jnimmo](https://github.com/jnimmo/hass-dmx) this worked fine, but now I can't have the same channel on different controllers:
```
2022-09-18 10:37:33.878 ERROR (MainThread) [homeassistant.components.light] Platform artnet_led does not generate unique IDs. ID 01 already exists - ignoring light.xxx
2022-09-18 10:37:33.879 ERROR (MainThread) [homeassistant.components.light] Platform artnet_led does not generate unique IDs. ID 05 already exists - ignoring light.yyy
...
```
Could this be incorporated?

**Comment by Breina** [comment]
Was a bit tricky to figure out how to change unique_ids without creating new entities (would be annoying for other users). But this will work now in v0.0.6.

Please make sure your device names are unique, it's using that as reference for migrating. Please let me know if it works for you. :)

**Comment by tobias-friedrich** [comment]
Thanks, @Breina! I couldn't safely test it due to hardware issues, but that's now resolved and it works fine. Thanks a lot for the swift fix!
