### ISSUE TITLE
Impossible to get white output (255, 255, 255)

### ISSUE THREAD

**Issue by mannaris** [Breina/ha-artnet-led#14]
I'm not able to select white as color. The fixtures just turn off.
I have some Stairville 240/8 fixtures and they have only RGB channels, so no white and also no dimmer.
(Screenshot for the first segment of one of them)
![image](https://user-images.githubusercontent.com/14327021/192891545-9bcdaa03-a074-41ed-93cb-3d7eafb8d9b8.png)

**Comment by Breina** [comment]
Fixed in v0.0.9
