### ISSUE TITLE
Added e1.31 sACN support 

### ISSUE THREAD

**Issue by Breina** [Breina/ha-artnet-led#15]
Refers to https://github.com/jnimmo/hass-dmx/pull/66

**Comment by jasonhargis** [comment]
Looking forward to sACN support. Is this being targeted for the next release? Thanks!

**Comment by Breina** [comment]
I don't have a timing for you, but I'll prioritize this after I finish the current client.

**Comment by Breina** [comment]
Hi @jasonhargis, this was added in v0.1.1, can you check if this works for you please?

**Comment by jasonhargis** [comment]
Hi @Breina, this is great news. YES I can confirm e1.31 sACN is now working in my environment. Thank you for all your efforts.  And should it help: I'm using an [ESPixelStick V3](https://forkineye.com/product/espixelstick-v3/) w/ V3.2 firmware, connected to this [DMX512](https://a.co/d/j0fMfTh) controller with 8x) RGBW LED strips.  Cheers!
