### ISSUE TITLE
default_level is not working

### ISSUE THREAD

**Issue by Mouse5312** [Breina/ha-artnet-led#16]
When I add the default_level to the configuration there is an error when checking the configuration.yaml.
Config:
        devices:
          - channel: 1
            name: LEDstrip on/off
            type: binary
            channel_size: 8bit            # width of the channel sent to DMX device, default "8bit", "16bit", "24bit" and "32bit" available.
            default_level: 0

Error:
Invalid config for [light.artnet_led]: [default_level] is an invalid option for [light.artnet_led]. Check: light.artnet_led->universes->0->devices->0->default_level. (See ?, line ?).

**Comment by fshubthunfischbaum** [comment]
Same here :'(

**Comment by Breina** [comment]
Indeed, it got removed by accident. It was only used when a state couldn't be restored after HA restarted, or when a new fixture was added. I guess that people were using it for static values.

Good news is that [charlie implemented a very clean solution](https://github.com/Breina/ha-artnet-led/pull/18) to support static light values. Is that what you guys were using this for?
