### ISSUE TITLE
Changing "name" field in configuration.yaml has no effect in HA

### ISSUE THREAD

**Issue by joshlawless** [Breina/ha-artnet-led#20]
I have a RGBWW strip setup that's working great with this HA integration.  I went into the configuration.yaml file today to change the "name" of one of my devices and restarted HA -- but this had no effect in HA; the previous name of the light persisted, and I can't see how to get HA to acknowledge the change.  

I changed the name from "master_shower" to "master_mirror" but HA still reflects the "light.master_shower" naming convention.  Normally I'd just rename the entity in HA, but I wanted to rename it in the artnet_led configuration so I could use the  WiFi easynode that I had previously set up for one set of LED strips for another, and free up the name for use with a second easynode.  

Appreciate any guidance

```
light:
  - platform: artnet_led
    host: 192.168.1.253                   # IP of Art-Net Node
    max_fps: 40                           # Max 40 per second
    refresh_every: 0                      # Resend values if no fades are running every x seconds, 0 disables automatic refresh
    universes:                            # Support for multiple universes
      0:                                  # Nr of Universe (see configuration of your Art-Net Node)
        devices:
          - channel: 1                    # first channel of dmx dimmer
            name: master_mirror           # name
            type: rgbww                   # type
            transition: 0                 # default duration of fades in sec. Will be overridden by Transition sent from HA
            output_correction: quadratic  # optional: quadratic, cubic or quadruple. Apply different dimming curves to the output. Default is None which means linear dimming
            channel_size: 16bit           # width of the channel sent to DMX device, default "8bit", "16bit", "24bit" and "32bit" available.
```

**Comment by Breina** [comment]
I've played around with it and haven't yet found a way to implement this without creating excess garbage (disabled/restored entities). For now, please just use the GUI to rename Entity ID's.
