### ISSUE TITLE
Trouble with multiple devices

### ISSUE THREAD

**Issue by joshlawless** [Breina/ha-artnet-led#22]
I have two easynode Wifi -> DMX antennas set up in this integration, and cannot get both to work reliably at the same time.  Inevitably, one of the two devices will respond intermittently to commands (e.g., ignoring 2 out of every three light_on service calls), while the other will respond instantly.  The identity of the device not behaving has changed - at first I thought I had a defective easynode, so I bought a third, and experienced the same problems with it (n.b., this is swapping the antenna out but retaining the power supply and DMX decoder box to which the LED strips are connected).  I tried changing IP addresses, universe numbers, deleting the integration and all entities associated with it, etc.  The easynode that used to work perfectly is now the one that doesn't behave, and the one that used not to behave is now the one that is consistent.   No error messages are thrown, but clicking around the color wheel or sliding brightness up and down is ignored.  Is there a debug mode I can utilize to try to solve this?  

Thanks!

**Comment by Breina** [comment]
You try can using debug logging, but don't expect much from it.

```
logger:
  logs:
    custom_components.artnet_led: debug
```

### Please verify that there's no packet loss at all to your nodes:

Windows: `ping -t IP_ADDRESS`

Linux/Mac: `ping IP_ADDRESS`

If both of your nodes get a perfect score, there isn't network loss

### Troubleshooting UDP traffic

You can check if your network specifically has trouble sending UDP traffic

For example this guide: https://linuxhandbook.com/udp-ping/

Your nodes should be able to connect on port 6454.

### Refresh interval

Try setting the `refresh_every` setting to 1, this will resend the values every second, making it tolerable if a packet gets missed.

### Investigate QoS on your router

UDP traffic might get filtered out in your router, check if disabling or tweaking the setting helps.

**Comment by joshlawless** [comment]
Ah, yep.  Network problem that's intermittent - huge UDP packet loss.  Thanks Breina (sincerely)!  And thanks Ubiquiti (ironically).
