### ISSUE TITLE
Feature Request - Dynamic Transition time

### ISSUE THREAD

**Issue by LighthouseMedia** [Breina/ha-artnet-led#25]
Be able to use another variable such as a helper or an internal variable that can be changed dynamically.

**Comment by Breina** [comment]
The current transition time is just a default one. If you want it dynamic, you could just use the `transition` attribute when calling [the light service](https://www.home-assistant.io/integrations/light/).

Please correct me if I'm misunderstanding, but I would think this is a cleaner solution than setting another variable, and then calling the light service without the `transition` attribute, no?

**Comment by Breina** [comment]
Does that work for you @LighthouseMedia ?

**Comment by LighthouseMedia** [comment]
Yes, I made a script and used a input number to contol how long i want the transisiton time to be. I also made the same scipt be able to work with any light, and even groups of lights.
