### ISSUE TITLE
Ran out of unique IDs for channels 

### ISSUE THREAD

**Issue by ShiranNYC** [Breina/ha-artnet-led#26]
Hello,

I am having an issue. I have a lot of channels needed over 2 universes. I am having an issue where we ran out of unique IDs for channels. Any help would be appreciated.

Thank you!

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:540
Integration: Light (documentation, issues)
First occurred: 5:21:47 PM (32 occurrences)
Last logged: 5:21:47 PM

Platform artnet_led does not generate unique IDs. ID dmx:10.111.1.44/1/40 is already used by light.speed_dimmer_par004 - ignoring light.static_gobo_vshow250_03
Platform artnet_led does not generate unique IDs. ID dmx:10.111.1.44/1/44 is already used by light.blue_dimmer_par005 - ignoring light.focus_vshow250_03
Platform artnet_led does not generate unique IDs. ID dmx:10.111.1.44/1/48 is already used by light.strobe_dimmer_par005 - ignoring light.program_vshow250_03
Platform artnet_led does not generate unique IDs. ID dmx:10.111.1.44/1/49 is already used by light.programs_dimmer_par005 - ignoring light.pan_vshow250_04
Platform artnet_led does not generate unique IDs. ID dmx:10.111.1.44/1/50 is already used by light.speed_dimmer_par005 - ignoring light.tilt_vshow250_04

Attached is a file with all the fixtures we have configured:
[lightsyaml.txt](https://github.com/Breina/ha-artnet-led/files/10946662/lightsyaml.txt)

**Comment by Breina** [comment]
I'm not exactly sure what the cause of this is yet, though the unique ID system is going to be revamped anyway.

Can you please do the following?

# First remove the integration
# Comment or remove the YAML config
# Restart
# Delete the light entities (search for `artnet_led` in on the entities page, so you can select all easily)
# Install this integration and re-introduce the config

That will create all entities anew and will work with the config your provided.

**Comment by ShiranNYC** [comment]
Thank you !I will try and report back!On Mar 11, 2023, at 1:32 AM, Breina ***@***.***> wrote:﻿
I'm not exactly sure what the cause of this is yet, though the unique ID system is going to be revamped anyway.
Can you please do the following?
First remove the integration
Comment or remove the YAML config
Restart
Delete the light entities (search for artnet_led in on the entities page, so you can select all easily)
Install this integration and re-introduce the config
That will create all entities anew and will work with the config your provided.

**Comment by ShiranNYC** [comment]
That worked! 

I have a separate question that I will put in a new thread.

Thanks again.
