### ISSUE TITLE
channel_setup bug

### ISSUE THREAD

**Issue by mattrcampbell** [Breina/ha-artnet-led#31]
The validate() method in custom_components/artnet_led/util/channel_switch.py rejects integers however the documentation says that static int values can be used to lock a value to a specific value.

**Comment by Breina** [comment]
Can you show your configuraiton of `channel_setup` please?

There's two ways to use it.

* As a string `channel_setup: Wrgb`
* As a list:
  ```
   channel_setup:
     - W
     - r
     - 128
     - b 
  ```

Only as a list, numbers are allowed.

**Comment by mattrcampbell** [comment]
See below, this causes an exception and a stack trace.  If I comment out the two static values, it loads fine.

`          - channel: 1
            name: snack_bar_sign
            type: rgb
            channel_setup:
              - d
              - 1 # width
              - 125 # speed
              - R
              - G
              - B
            output_correction: linear
            channel_size: 8bit
`

**Comment by Breina** [comment]
Got it, I can reproduce your issue. Let me fix that!

**Comment by Breina** [comment]
Fixed in v0.1.8, please verify and report back! :)

**Comment by mattrcampbell** [comment]
That fixed it!  Thanks so much!
