### ISSUE TITLE
Refresh is not working

### ISSUE THREAD

**Issue by m7r** [Breina/ha-artnet-led#36]
I found an issue while running a longer theater show on the [avr node](https://www.ulrichradig.de/home/index.php/dmx/alias-2).
This interface require an regular refresh. iI it got no update for several minutes it sends an artnet poll and unfortunately sometimes an defect dmx frame with unexpected changes to the lights.

I fixed it by changing the code to
```python
refresh_interval > 0
```
https://github.com/Breina/ha-artnet-led/blob/65b48fb894ff9002dce557742cd7a078dc560a70/custom_components/artnet_led/light.py#L100

**Comment by Breina** [comment]
Awesome, thanks for pointing that out! :)


Do you want to create a PR for this so you appear in the list of contributors, or prefer if I just fix it directly?

**Comment by m7r** [comment]
Thanks for the fast merge.
