### ISSUE TITLE
sACN not working

### ISSUE THREAD

**Issue by BenJamesAndo** [Breina/ha-artnet-led#38]
Hello. I have some DMX lights that are controllable via an [ENTECC ODE Mk2](https://support.enttec.com/support/solutions/articles/101000438016-ode-mk2-70405-70406-) controller which supports either Art-net or sACN. I've been using ha-artnet-led with art-net for over a year and it's been great. I'm wanting to switch to sACN as another program that I want to use on occasions only supports sACN. Having switch the controller to sACN I can get two different lighting software to control it. However with ha-artnet-led nothing happens.

I've tried setting it to the wrong universe and sure enough ha-artnet-led entities go offline. However when everything is configured correctly I can adjust the lights in HA but nothing happens. Checking the logs in the ODE Mk2 controller and it's not getting any data packets received.
I've even tried using a fresh install of HA and setting it all up from scratch. Any ideas on how I can get this to work?

Below is my config. I can't see any error logs in HA.

~~~light:
  - platform: artnet_led
    host: 192.168.1.29
    max_fps: 40
    node_type: sacn    
    universes: 
      1:   
        send_partial_universe: True 
        devices:
          - channel: 1
            name: Back lights
            type: dimmer
            transition: 0.5
          - channel: 2
            name: Front left
            type: dimmer            
          - channel: 3
            name: Front middle
            type: dimmer
            transition: 0.5
          - channel: 4
            name: Front right
            type: dimmer
            transition: 0.5
          - channel: 6
            name: Back Far L&R
            type: dimmer
            transition: 0.5
          - channel: 7
            name: Back left
            type: dimmer
            transition: 0.5
          - channel: 8
            name: Back right
            type: dimmer
            transition: 0.5
          - channel: 13
            name: Red LED
            type: rgb
            transition: 1

~~~

**Comment by Breina** [comment]
Thanks for the good bug report!

Don't have time at this moment to investigate, give me a bit so that I can replicate. I will try to do this this in the weekend.

If you've set it up from scratch, without retaining the old light entities, there's definitely something wrong code-wise.

My ENTTEC device has a bug that makes it ignore the last few (up to 5) bytes of a sACN packet, so it's a good idea to set `send_partial_universe: False`. Raised this issue to them half a year ago, I requested an update from them.

**Comment by BenJamesAndo** [comment]
Well that's convenient that you have the same branded device as me. I tried with `send_partial_universe: False` but it didn't make any difference.

Unfortunately my device reached end of life support last year so even if ENTTEC did fix the bug your reported I doubt I'd get it in a firmware update.

**Comment by Breina** [comment]
We were using a bad default port for sACN. If you use `port: 5568`, then it does work.

Changed the default port of sACN to reflect this, will release in a bit.

**Comment by Breina** [comment]
Alright `v0.1.12` is up for you. Please test. :)

**Comment by BenJamesAndo** [comment]
Thanks for this. Tested and works great now!
