### ISSUE TITLE
DMX-in almost working / "port address we don't care about"

### ISSUE THREAD

**Issue by Fred-DTV** [Breina/ha-artnet-led#40]
Hi Breina,

After a long time I finally found some time to continue my project with your integration.

The good nes is that my DMX controll software Madrix now discovers the integration as new art-net node and even shows the correct amount of universes.
Also on the other hand, the integration in HA reports, that it is connected to the Madrix software.

I have mapped a 1ch fixture to the example my_dimmer light on channel 1 in universe 1 (set the universe in the config.yaml to 1) but it doesn't receive any values.

This is the log output:
`2023-07-08 23:26:53.740 DEBUG (MainThread) [custom_components.artnet_led.client.artnet_server] Received ArtDmx for port address that we don't care about: 0:0:0
2023-07-08 23:26:53.742 WARNING (MainThread) [custom_components.artnet_led.client.artnet_server] Received Opcode OpCode.OP_SYNC, which isn't supported yet!`

P.S.: I saw in the log that the integration is polling a lot, that's why warnings like the Opcode one show up 10.000 times within a couple of minutes. 
I think this could be an issue why I wasn't able to get it running on my old Pi3b, which crashed everytime I installed the integration. Now I have it running in a VM which can handle a lot more, however, this probably needs some refininf (which unfortunately I have no idea of...)

**Comment by Breina** [comment]
The first warning is saying that it received DMX data for universe 0 (`net:subnet:universe`), not universe 1. As thus, Madrix is sending to the wrong universe.

The `OP_SYNC` opcode is used to sync up several ArtNet controllers to the same timing. This is for example used for syncing up big panels. Is there a setting in Madrix to disable this?

If you desire this, I can look into implementing it. Shouldn't be too hard.

**Comment by Fred-DTV** [comment]
Ahhh okay I understand now. 
Madrix does show the Universe and DMX Channels starting from 1 in the UI while Art-Net starts at 0

However, It is working now! :)
There is not even a noticeable delay. This is amazing.
We are a small nightclub and having the possibility to control basically any smart light (or device) by DMX via Madrix, opens up a whole new dimension of light shows. 
Thanks a lot for your work!
If you'd like me to test anything further just let me know. 

Regarding OPSync: I don't need it and I've just disabled it in Madrix (it was on by default)

**Comment by Breina** [comment]
Glad to hear! :)

**Comment by Breina** [comment]
Btw, I've been playing around with computationally generating light shows; https://www.youtube.com/watch?v=zZtRdKxHvpI

It's in the back of my head to port this over so that it works with HA. Would be cool to see that in an actual night club someday. :D

**Comment by Fred-DTV** [comment]
That's pretty dope :)

The reason why we are using Madrix, is because it has these super easy functions to create light shows just like you did there, based on either sound frequency volume or musical notes. So something like that is fairly easy to do with Madrix

**Comment by Breina** [comment]
Ah, I figured that the DMX community has that problem already solved. Perhaps it's smarter to just export my shows into Madrix, so that they can be used and tuned as-is.

There's a huge repository (50k songs or something) of already synced note timings from the rythm game community. I'm just leeching of that, I'm not actually reading the music itself.
