### ISSUE TITLE
Broadcasting address / flag

### ISSUE THREAD

**Issue by rikkertkoppes** [Breina/ha-artnet-led#41]
As I understand broadcasting is already supported in pyArtNet in version 0.8.2

However, the call to the node constructor does not include that flag: https://github.com/Breina/ha-artnet-led/blob/7969ddadab2df30cc5b89655d2ce83246daa00c9/custom_components/artnet_led/light.py#L112

I tested by setting the host to 192.168.2.255 (my subnet mask is 255.255.255.0) and HA does not seem to output any udp packets with this setting (tested with wireshark)

Is this implemented? If so, what am I missing?. If not, can it be?

**Comment by Breina** [comment]
It was added in 0.8.2, but was (rightfully) removed in 1.0.1.

A correct Art-Net implementation does not broadcast DMX data:

![image](https://github.com/Breina/ha-artnet-led/assets/3009914/c9e82e0c-3a78-47a1-b742-52efe8e88d07)

Can you share what it is that requires you to attempt to broadcast DMX data? If you have multiple properly functioning Art-Net nodes, try setting `node_type: artnet-controller` instead (in such case, the IP is ignored).

**Comment by rikkertkoppes** [comment]
I am working on a ledstrip controller that runs on esp32 devices. They allow custom effects and led mappings for which dmx channels can be input parameters. 

There may be multiple such devices, which all get loaded beforehand with the same set of effects, so these effects all listen to the same channels and universes. One channel may for instance control "speed" of the effect. Other channels may control an rgb color in the effect.

Since all devices share the same set of effects, giving them separate channel spaces (and then sending the same value to those channels, as if it were different fixtures) is not possible without hardware modifications. 

Basically, all the devices (with different ip addresses) may be thought of as one fixture. 

I have successfully made this to work using QLC+, which does broadcast artnet over udp, but I'm now seeking to bring this into home assistant.

Some other solutions I can think of are:
1. using some message bus rather than artnet, but making them work on dmx is a nice feature
2. adding hardware dipswitches to define an address offset for each device, essentially making them multiple fixtures
3. creating some dedicated hardware that listens to unicasted messages and re-broadcast them
4. changing ha-artnet to allow multiple host addresses
5. changing ha-artnet to allow one entity to control multiple channels in combination with 2. (e.g one dimmer slider controlling the dimmer value for the now-separated fixtures)

Do you maybe have other suggestions to make this work?

**Comment by Breina** [comment]
Just exploring options here..

6. If your ESP32 ledstrip controller supports the Art-Net Poll mechanism, it will be picked up if you set `node_type: artnet-controller` and it will send packets to all of them individually.
7. If they don't, you can duplicate your config with multiple artnet_led platforms with different IP's, same channels and `node_type: artnet-direct`. Then link them up through a HA automation.
8. Just allowing broadcasting. I don't necessarily see any technical problems with it, only deviating from the spec. This is a change that's necessary in [PyArtNet](https://github.com/spacemanspiff2007/PyArtNet) though, ha-artnet-led will just pass through the option in that case.

I'm sending an email to Artistic License to check what their reasoning is on this.

**Comment by rikkertkoppes** [comment]
Thanks for your reply. I am quite new to artnet and udp in general, so I will investigate implementing the artpoll mechanism. This seems the cleanest way to go.

As another approach, would udp multicasts work?

**Comment by Breina** [comment]
Oh that's pretty cool! That's good to know. :)

ArtPoll is a lot of work to implement, that's not going to be worth it anyway.

**Comment by Breina** [comment]
Response from Artistic License;

> Good morning and thanks for your email.
> 
> For historical reasons it was decided that constant broadcasting would be more than problematic:
> 
> Of course you could choose to broadcast and I’m sure in that very specific situation where you have multiple receivers wanting to see the same single universe, it will be fine.
> 
> The reason we forbid it is very simple: Expand that logic to 2, 5 ,10 ,100, 1000 universes. The network and network devices will be overrun.
> 
> Hope that answers your question.
> 
> If you’re interested in the theory from a developers perspective, I can recommend Wayne Howell’s book – Light Bytes.  Link below
> 
> https://artisticlicence.com/product/light-bytes/

Seeing as your issue is solved, I'll close this ticket for now until someone really needs broadcast, not multicast.
