### ISSUE TITLE
Follow up https://github.com/jnimmo/hass-dmx/issues/65

### ISSUE THREAD

**Issue by Breina** [Breina/ha-artnet-led#5]
https://github.com/jnimmo/hass-dmx/issues/65

@PanBlaza

>I tried your method today and good news is: led is receiving a signal. However I have met some problem: I tried it on first channel, i made just PIXEL 1 but it came not only on 1 pixel but also on the second one. It looks like these channels were connected. Moreover, the colour that appeared was different than the one I had chosen earlier (because they are connected now, I guess)

**Comment by Breina** [comment]
Just make sure; can you share your config again?

>It looks like these channels were connected.

Please verify that the channels on your device are configured properly and not overlapping. Are your channels 8 bit, or 16 bit?

**Comment by PanBlaza** [comment]
YEAAAH its 8bit, everything is works now :) Many thanks Breina: D

**Comment by Breina** [comment]
Happy to help! :)

**Comment by PanBlaza** [comment]
Hi again :)
I have met another trouble recently. It is about the dimmer on leds. When I want to change a level of brightness, it works like:  0% is 0 (no light) and 1-100% of it is full light. No matter which I chose (except 0) it's going to full brightness. Any ideas? Thx in advance! :)

**Comment by Breina** [comment]
Can you please share what device your DMX driver is? Then I can have a look at its spec.

**Comment by PanBlaza** [comment]
This one: https://yarilo.pro/en/controllers/art-net-dmx/yarilo-landmx2
Thank you

**Comment by Breina** [comment]
Ah I mean of the DMX device itself, not the interface.

**Comment by PanBlaza** [comment]
Ok understand,
Led strip is this one: https://www.alibaba.com/product-detail/2020-Newest-rgb-dmx-adressable-led_62034933873.html?spm=a2700.shop_plgr.41413.9.44552f27PvjMtE
also same problem with rgbw decoder with brightness:
https://pl.aliexpress.com/item/4000972563757.html?spm=a2g0o.productlist.0.0.106f5af4gnKb0T&algo_pvid=7261796e-c3d4-4327-bd9a-f37518b8ef48&algo_exp_id=7261796e-c3d4-4327-bd9a-f37518b8ef48-11&pdp_ext_f=%7B%22sku_id%22%3A%2212000028423415528%22%7D&pdp_npi=2%40dis%21PLN%21105.01%2191.37%21%21%2119.54%21%21%402100bdd816620199291608369e72a7%2112000028423415528%21sea&curPageLogUid=u5OutAisdCwd
but on jnimmo's everything was ok just colour was rgb not rbg on led strip

**Comment by Breina** [comment]
Fixed in the latest version; please update to v0.0.3 and let me know if it works for you. :)

**Comment by PanBlaza** [comment]
Hi Brenna,

Everything is working now, thank you :))
