### ISSUE TITLE
Platform error light.artnet_led - cannot import name 'ATTR_COLOR_TEMP_KELVIN' from 'homeassistant.components.light' 

### ISSUE THREAD

**Issue by jgrabitzky** [Breina/ha-artnet-led#51]
After installation of the plugin and editing the configuration.yaml to 

light:
  - platform: artnet_led
    host: 192.168.111.123
    max_fps: 25                           # Max 40 per second
    refresh_every: 0
    node_type: artnet-controller                      # Resend values if no fades are running every x seconds, 0 disables automatic refresh
    universes:                            # Support for multiple universes
      1:                                  # Nr of Universe (see configuration of your Art-Net Node)
        devices:
        #Dimmer
          - channel: 1                    # first channel of dmx dimmer
            name: LED Bar               # name
            type: dimmer                  # type
            channel_size: 8bit
            channel_setup: rgb

test the configuration.

Error:

Konfiguration überprüfen
Überprüfen Sie Ihre Konfiguration, wenn Sie kürzlich Änderungen vorgenommen haben und sicherstellen möchten, dass alle Änderungen gültig sind
Konfiguration fehlerhaft 

  Platform error light.artnet_led - cannot import name 'ATTR_COLOR_TEMP_KELVIN' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

This is my Homeassistant:

## System Health

version | core-2022.3.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.0-12-amd64
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1367
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

Thanks for help

**Comment by Breina** [comment]
Any chance you can update your HomeAssistant? The current version of the integration is no longer compatible with this older one I'm afraid.

**Comment by Breina** [comment]
Closing issue: old HA version no longer supported
