### ISSUE TITLE
using deprecated supported features values LightEntityFeature.FLASH|TRANSITION

### ISSUE THREAD

**Issue by hkusulja** [Breina/ha-artnet-led#52]
Hello,
I have started using this great addon. However in logs there are warnings that should be resolved, therefore opening this Issue.

> 2024-01-14 18:55:12.834 WARNING (MainThread) [homeassistant.components.light] Entity light.my_rgbww_lamp1 (<class 'custom_components.artnet_led.light.DmxRGBWW'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.FLASH|TRANSITION: 40> and color modes, please create a bug report at https://github.com/Breina/ha-artnet-led/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by djripcord** [comment]
Can confirm this is a problem and am seeing the same errors in logs. Right now, this is not a fatal bug, but it needs to be fixed before the end of 2024.

**Comment by Breina** [comment]
Fixed in v0.1.20

Please test :)

**Comment by hkusulja** [comment]
i am new to HACS etc., i need to learn how to change from main branch to this (which?) test branch, I will test, tx

**Comment by Breina** [comment]
HACS > Integrations > Art-net LED Lighting for DMX > Update > Update

![image](https://github.com/Breina/ha-artnet-led/assets/3009914/85249cf1-0fa5-41ff-bbce-5eef48c8cb12)

**Comment by hkusulja** [comment]
Resolved.

**Comment by hkusulja** [comment]
Resolved
