### ISSUE TITLE
New to DMX/ArtNet, would this work?

### ISSUE THREAD

**Issue by millercentral** [Breina/ha-artnet-led#57]
I'm planning a new RGBWW LED Strip project, and I am looking for controllers that would work with this project. Anyone know if these should work?

- Controller: [FlexFireLED 5-Channel DMX512 Decoder](https://www.flexfireleds.com/dmx-control-systems/5-channel-dmx512-decoder/) -- this is compatible with the RGBWW LED strip I'm using.
- Art.Net interface: [ArtNet bi-directional DMX Ethernet Lighting Control Interface](https://www.amazon.com/Pknight-bi-directional-Ethernet-Controller-Interface/dp/B0B1YRTYB7) 

Seems like this would work, but want to confirm...  Thanks!

**Comment by Breina** [comment]
Sorry for the late reply, I didn't see this one.

Please post this on the forum thread; there's bound to be more eyes on your request there: https://community.home-assistant.io/t/dmx-lighting/2248/494
